#pragma once

/*
 * German (de-DE) localized keycodes.
 *
 * Start from the existing local Swiss mapping and override keys that differ
 * for common de-DE usage in this keymap.
 */
#include "keys_de_swiss.h"

/* § on DE-DE: Shift+3 */
#undef DE_SECTION
#undef DE_SECT
#define DE_SECTION (LS(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_3_AND_HASH)))
#define DE_SECT (DE_SECTION)

/* ° on DE-DE: Shift+^ key (US grave position) */
#undef DE_DEGREE
#undef DE_DEG
#define DE_DEGREE (LS(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_GRAVE_ACCENT_AND_TILDE)))
#define DE_DEG (DE_DEGREE)

/* µ on DE-DE: AltGr+M */
#ifndef DE_MICRO
#define DE_MICRO (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_M)))
#endif
#ifndef DE_MU
#define DE_MU (DE_MICRO)
#endif

/* @ on DE-DE: AltGr+Q */
#undef DE_AT_SIGN
#undef DE_AT
#define DE_AT_SIGN (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_Q)))
#define DE_AT (DE_AT_SIGN)

/* ! on DE-DE: Shift+1 */
#undef DE_EXCLAMATION
#undef DE_EXCL
#define DE_EXCLAMATION (LS(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_1_AND_EXCLAMATION)))
#define DE_EXCL (DE_EXCLAMATION)

/* + and * on DE-DE share the key right of Ü */
#undef DE_PLUS
#define DE_PLUS (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_BRACE))
#undef DE_ASTERISK
#undef DE_STAR
#define DE_ASTERISK (LS(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_BRACE)))
#define DE_STAR (DE_ASTERISK)

/* | on DE-DE: AltGr+< */
#undef DE_PIPE
#define DE_PIPE (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_NON_US_BACKSLASH_AND_PIPE)))

/* { and } on DE-DE: AltGr+7 / AltGr+0 */
#undef DE_LEFT_BRACE
#undef DE_LBRC
#define DE_LEFT_BRACE (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_7_AND_AMPERSAND)))
#define DE_LBRC (DE_LEFT_BRACE)

#undef DE_RIGHT_BRACE
#undef DE_RBRC
#define DE_RIGHT_BRACE (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_0_AND_RIGHT_PARENTHESIS)))
#define DE_RBRC (DE_RIGHT_BRACE)

/* [ ] and \ on DE-DE via AltGr */
#undef DE_LEFT_BRACKET
#define DE_LEFT_BRACKET (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_8_AND_ASTERISK)))
#undef DE_RIGHT_BRACKET
#define DE_RIGHT_BRACKET (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_9_AND_LEFT_PARENTHESIS)))
#undef DE_BACKSLASH
#define DE_BACKSLASH (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_MINUS_AND_UNDERSCORE)))

/* Dead keys on DE-DE */
#undef DE_CARET
#define DE_CARET (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_GRAVE_ACCENT_AND_TILDE))
#undef DE_ACUTE
#define DE_ACUTE (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_EQUAL_AND_PLUS))

/* Diaeresis dead key (for ë/ï) */
#undef DE_UMLAUT
#define DE_UMLAUT (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_LEFT_BRACKET_AND_LEFT_BRACE)))

/* ~ on DE-DE: AltGr + '+' key */
#undef DE_TILDE
#define DE_TILDE (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_BRACE)))

/* ß on DE-DE is the US '-' key position */
#undef DE_SHARP_S
#define DE_SHARP_S (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_MINUS_AND_UNDERSCORE))
#undef DE_SS
#define DE_SS (DE_SHARP_S)

/* £ on DE-DE commonly via AltGr+Shift+3 */
#undef DE_POUND_SIGN
#undef DE_POUND
#define DE_POUND_SIGN (LS(RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_3_AND_HASH))))
#define DE_POUND (DE_POUND_SIGN)

/* ¥ on DE-DE commonly via AltGr+Y (letter key) */
#undef DE_YEN
#define DE_YEN (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_Y)))
/* ç (if layout supports it) */
#undef DE_C_CEDILLA
#define DE_C_CEDILLA (RA(ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_COMMA_AND_LESS_THAN)))
